name: anime_slide_puzzle
description: Flutter Slide Puzzle

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  equatable: ^2.0.3
  collection: ^1.16.0
  tuple: ^2.0.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
    - family: BubblegumSans
      fonts:
        - asset: fonts/BubblegumSans-Regular.ttf
